version: 2.1

orbs:
  hub: mattvanstone/hub@dev:alpha
  cli: circleci/circleci-cli@0.1.6

jobs:
  validate:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - cli/install
      - run:
          name: Validate
          command: circleci orb validate hub.yml
  test-install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - hub/install
      - run: hub --version
  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - cli/install
      - run:
          name: Publish
          command: circleci orb publish hub.yml ${CIRCLE_PROJECT_USERNAME}/hub@dev:alpha
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - cli/install
      - run: |
          current=$(circleci orb info ${CIRCLE_PROJECT_USERNAME}/hub | grep Latest | sed 's/^.*@//')
          git log --no-merges --pretty=format:"%s %h" v${current}..HEAD >> message_body
      - run: circleci orb publish promote ${CIRCLE_PROJECT_USERNAME}/hub@dev:alpha patch
      - hub/install
      - run:
          name: Create release
          command: |
            released=$(circleci orb info ${CIRCLE_PROJECT_USERNAME}/hub | grep Latest | sed 's/^.*@//')
            echo "Release v${released}"  > message
            echo ""                     >> message
            cat message_body            >> message
            timeout 30 hub release create -F message -t release v${released}

workflows:
  test:
    jobs:
      - validate
      - test-install
  publish:
    jobs:
      - publish:
          context: circleci-hub-orb
          filters:
            branches:
              only:
                - master
  release:
    jobs:
      - release:
          context: circleci-hub-orb
          filters:
            branches:
              only:
                - release
