version: 2.1

orbs:
  hub: yasuhiroki/hub@dev:alpha
  cli: circleci/circleci-cli@0.1.6

jobs:
  validate:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - cli/install
      - run: circleci orb validate hub.yml
  test-install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - hub/install
      - run: hub --version
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - cli/install
      - run: circleci orb publish hub.yml yasuhiroki/hub@dev:alpha
      - hub/install
      - run: timeout 30 hub release create -d -m latest -t release dev-alpha

workflows:
  test:
    jobs:
      - validate
      - test-install
  release:
    jobs:
      - release:
          context: yasuhiroki
          filters:
            branches:
              only:
                - release
